name: ahorro_app
description: "App móvil para control de gastos y ahorros"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # Iconos de Material Design
  cupertino_icons: ^1.0.8

  # Para gráficos y estadísticas
  fl_chart: ^0.68.0

  # Para manejo de fechas
  intl: ^0.20.2

  # Para localización
  flutter_localizations:
    sdk: flutter

  # Para persistencia de datos local
  shared_preferences: ^2.2.2

  # Para modelos de datos
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Para generar código de modelos
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

  # Para generar íconos de la app automáticamente
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets de la aplicación
  assets:
    - assets/images/
    - assets/icons/

# Configuración para generar íconos automáticamente  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/new_icon_image.jpg"  # Cambiado a JPG
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/new_icon_image.jpg"  # Cambiado a JPG
  windows:
    generate: true
    image_path: "assets/icons/new_icon_image.jpg"  # Cambiado a JPG
  macos:
    generate: true
    image_path: "assets/icons/new_icon_image.jpg"  # Cambiado a JPG